name: Request Challenge with JSON Header

on:
  push:
    branches:
      - main

jobs:
  send-request:
    runs-on: ubuntu-latest

    steps:
    - name: Send HTTP Request with JSON Header
      run: |
        curl -s -H "Content-Type: application/json" -o response.txt -w "%{http_code}" https://actions.ctf.cert.unlp.edu.ar
        cat response.txt
